AllCops:
  Exclude:
    - spec/dummy/db/schema.rb
    - vendor/bundle/**/*

Documentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Lint/NestedMethodDefinition:
  Exclude:
    - lib/active_admin_chat/active_admin/application.rb

Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be an Integer or
  # a Float.
  Max: 15
  Exclude:
    - lib/generators/active_admin_chat/install/install_generator.rb
    - lib/active_admin_chat/active_admin/application.rb
    - app/channels/chat_channel.rb

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 25
  Exclude:
    - spec/generators/install_generator_spec.rb
    - lib/active_admin_chat/active_admin/application.rb
  ExcludedMethods: ['describe', 'context', 'feature', 'scenario']

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 200

# Avoid complex methods.
Metrics/CyclomaticComplexity:
  Max: 6

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 24
  Exclude:
    - lib/active_admin_chat/active_admin/application.rb

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 200

Metrics/LineLength:
  Max: 100
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https
  Exclude:
    - spec/dummy/**/*
    - spec/channels/chat_channel_spec.rb
    - config/routes.rb

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 12

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - spec/dummy/bin/*

Style/GuardClause:
  Exclude:
    - lib/generators/active_admin_chat/install/install_generator.rb
