language: ruby
cache: bundler
rvm:
  - 2.5.1

sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
